#Medical_Students_Data

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/medical_students_dataset.csv",encoding="ISO-8859-1")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      180000 non-null  float64
 1   Age             180000 non-null  float64
 2   Gender          180000 non-null  object
 3   Height          180000 non-null  float64
 4   Weight          180000 non-null  float64
 5   Blood Type      180000 non-null  object
 6   BMI             180000 non-null  float64
 7   Temperature     180000 non-null  float64
 8   Heart Rate      180000 non-null  float64
 9   Blood Pressure  180000 non-null  float64
 10  Cholesterol     180000 non-null  float64
 11  Diabetes        180000 non-null  object
 12  Smoking         180000 non-null  object
dtypes: float64(9), object(4)
memory usage: 19.8+ MB

In [6]:
df['Student ID'].unique()

array([1.0000e+00, 2.0000e+00, 3.0000e+00, ..., 9.9961e+04, 9.9994e+04,
       9.9997e+04])

In [7]:
df["Age"].unique()

array([18., nan, 32., 30., 23., 21., 28., 34., 29., 33., 24., 27., 31.,
       22., 25., 20., 19., 26.])

In [8]:
#Handling Age
df["Age"]=df["Age"].replace(np.nan,0)
df["Age"]=df["Age"].astype(float)
avg_age=round(df["Age"].mean())
df["Age"]=df["Age"].replace(0,avg_age)
df["Age"].unique()

array([18., 23., 32., 30., 21., 28., 34., 29., 33., 24., 27., 31., 22.,
       25., 20., 19., 26.])

In [9]:
df["Gender"].unique()
df["Gender"] = df["Gender"].fillna("Not disclosed")
df["Gender"].unique()

array(['Female', 'Male', 'Not disclosed'], dtype=object)

In [10]:
df["Height"].unique()

array([161.77792424, 152.06915679, 182.53766352, ..., 195.40741561,
       183.49917658, 159.48690665])

In [11]:
df["Weight"].unique()

array([72.35494708, 47.6309415 , 55.74108279, ..., 70.73265934,
       80.18875193, 80.82857721])

In [12]:
df["Blood Type"].unique()

array(['O', 'B', 'A', 'AB', nan], dtype=object)

In [13]:
#Handling Blood Type
df["Blood Type"] = df["Blood Type"].fillna(df["Blood Type"].mode()[0])
df["Blood Type"].unique()

array(['O', 'B', 'A', 'AB'], dtype=object)

In [14]:
df["BMI"].unique()

array([27.64583507,         nan, 16.72901714, ..., 12.31016852,
       33.92803976, 19.73346463])

In [15]:
#Handling BMI
df["BMI"] = df["BMI"].fillna(df["BMI"].median())
df["BMI"].unique()

array([27.64583507, 22.67140145, 16.72901714, ..., 12.31016852,
       33.92803976, 19.73346463])

In [16]:
df['Temperature'].unique()

array([        nan, 98.71497675, 98.26029302, ..., 98.35391685,
       98.33101869, 99.17068488])

In [17]:
#Handling Temperature
df["Temperature"] = df["Temperature"].fillna(df["Temperature"].mean())
df["Temperature"].unique()

array([98.60094788, 98.71497675, 98.26029302, ..., 98.35391685,
       98.33101869, 99.17068488])

In [18]:
df["Heart Rate"].unique()

array([95., 93., 76., 99., 70., 66., 85., nan, 61., 60., 86., 62., 89.,
       68., 63., 78., 92., 82., 64., 81., 96., 98., 80., 77., 67., 74.,
       75., 73., 84., 65., 97., 90., 87., 88., 69., 94., 71., 79., 72.,
       91., 83.])

In [19]:
#Handling Heart Rate
df["Heart Rate"] = df["Heart Rate"].fillna(df["Heart Rate"].median())
df["Heart Rate"].unique()

array([95., 93., 76., 99., 70., 66., 85., 80., 61., 60., 86., 62., 89.,
       68., 63., 78., 92., 82., 64., 81., 96., 98., 77., 67., 74., 75.,
       73., 84., 65., 97., 90., 87., 88., 69., 94., 71., 79., 72., 91.,
       83.])

In [20]:
df["Blood Pressure"].unique()

array([109., 104., 130., 112.,  nan, 128., 134., 123., 111.,  94.,  97.,
       133., 126., 135., 102.,  96., 101., 124., 108., 132., 115.,  95.,
        93., 125., 122., 116., 127., 103., 129.,  99., 105., 121., 119.,
       136., 113.,  92., 110., 114., 106., 118., 120., 107., 137., 117.,
        98., 100., 131.,  91.,  90., 138., 139.])

In [21]:
#Handling Blood Pressure
df["Blood Pressure"] = df["Blood Pressure"].fillna(df["Blood Pressure"].median())
df["Blood Pressure"].unique()

array([109., 104., 130., 112., 115., 128., 134., 123., 111.,  94.,  97.,
       133., 126., 135., 102.,  96., 101., 124., 108., 132.,  95.,  93.,
       125., 122., 116., 127., 103., 129.,  99., 105., 121., 119., 136.,
       113.,  92., 110., 114., 106., 118., 120., 107., 137., 117.,  98.,
       100., 131.,  91.,  90., 138., 139.])

In [22]:
df["Cholesterol"].unique()

array([203., 163., 216., 141., 231., 183., 247., 128., 243., 166., 241.,
       246., 180., 130., 197., 161., 172., 223., 176.,  nan, 227., 217.,
       123., 147., 219., 242., 165., 186., 215., 214., 143., 152., 233.,
       177., 236., 157., 127., 135., 142., 170., 146., 232., 199., 137.,
       139., 240., 174., 149., 237., 192., 151., 150., 201., 159., 228.,
       206., 181., 205., 134., 212., 198., 133., 190., 156., 164., 210.,
       221., 171., 154., 178., 160., 200., 220., 211., 213., 162., 148.,
       145., 209., 202., 169., 189., 129., 249., 182., 126., 239., 224.,
       185., 238., 187., 230., 229., 168., 222., 196., 136., 208., 125.,
       191., 244., 184., 173., 131., 144., 245., 132., 175., 122., 167.,
       124., 234., 248., 225., 235., 207., 179., 188., 194., 195., 158.,
       138., 153., 155., 204., 218., 226., 121., 120., 193., 140.])

In [23]:
#Handling Cholesterol
df["Cholesterol"] = df["Cholesterol"].fillna(df["Cholesterol"].median())
df["Cholesterol"].unique()

array([203., 163., 216., 141., 231., 183., 247., 128., 243., 166., 241.,
       246., 180., 130., 197., 161., 172., 223., 176., 184., 227., 217.,
       123., 147., 219., 242., 165., 186., 215., 214., 143., 152., 233.,
       177., 236., 157., 127., 135., 142., 170., 146., 232., 199., 137.,
       139., 240., 174., 149., 237., 192., 151., 150., 201., 159., 228.,
       206., 181., 205., 134., 212., 198., 133., 190., 156., 164., 210.,
       221., 171., 154., 178., 160., 200., 220., 211., 213., 162., 148.,
       145., 209., 202., 169., 189., 129., 249., 182., 126., 239., 224.,
       185., 238., 187., 230., 229., 168., 222., 196., 136., 208., 125.,
       191., 244., 173., 131., 144., 245., 132., 175., 122., 167., 124.,
       234., 248., 225., 235., 207., 179., 188., 194., 195., 158., 138.,
       153., 155., 204., 218., 226., 121., 120., 193., 140.])

In [24]:
df["Diabetes"].unique()

array(['No', 'Yes', nan], dtype=object)

In [25]:
#Handling Diabetes
df["Diabetes"] = df["Diabetes"].fillna(df["Diabetes"].mode()[0])
df["Diabetes"].unique()

array(['No', 'Yes'], dtype=object)

In [26]:
df["Smoking"].unique()

array([nan, 'No', 'Yes'], dtype=object)

In [27]:
#Handling Smoking
df["Smoking"] = df["Smoking"].fillna(df["Smoking"].mode()[0])
df["Smoking"].unique()

array(['No', 'Yes'], dtype=object)

In [28]:
df.shape

(200000, 13)

In [29]:
#Dropping Duplicates
df.drop_duplicates(inplace=True)
df.shape

(188385, 13)

In [30]:
#6)Handling missing values
df.dropna(inplace=True)
df.isnull().sum()

Student ID        0
Age               0
Gender            0
Height            0
Weight            0
Blood Type        0
BMI               0
Temperature       0
Heart Rate        0
Blood Pressure    0
Cholesterol       0
Diabetes          0
Smoking           0
dtype: int64

In [31]:

#10) Resetting the index
df.reset_index(inplace=True)
df=df.drop("index",axis=1)
df

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.0,Female,161.777924,72.354947,O,27.645835,98.600948,95.0,109.0,203.0,No,No
1,2.0,23.0,Male,152.069157,47.630941,B,22.671401,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.0,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,6.0,32.0,Not disclosed,151.491294,68.647805,B,29.912403,99.668373,70.0,128.0,183.0,No,Yes
4,7.0,21.0,Not disclosed,172.949704,48.102744,AB,16.081635,97.715469,66.0,134.0,247.0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
134554,99991.0,21.0,Female,183.735110,51.172076,AB,15.158238,97.998790,67.0,96.0,249.0,No,Yes
134555,99993.0,34.0,Male,161.590030,90.877589,B,34.803881,98.728836,70.0,96.0,208.0,No,No
134556,99997.0,29.0,Female,163.917675,45.225194,B,16.831734,97.865785,62.0,125.0,198.0,No,Yes
134557,99999.0,30.0,Female,156.446944,50.142824,A,20.486823,98.994212,61.0,106.0,225.0,No,No
134558,100000.0,20.0,Female,153.927409,99.928405,O,42.175189,98.595817,95.0,133.0,132.0,No,No